### ISSUE TITLE
OpenClonk fails to start with AMD Renoir GPU

### ISSUE THREAD

**Issue by rugk** [openclonk/openclonk#143] opened 2020-06-07 17:40 UTC
I hope it is okay to use GitHub for reporting bugs. I did not want to get https://bugs.openclonk.org to work. (If I should repost it there, feel free to let me know.)

## STR

Start OpenClonk.

What happens:

```
$ flatpak run org.openclonk.OpenClonk
libGL error: pci id for fd 7: 1002:1636, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
[19:24:35] OpenClonk
[19:24:35] Version: 8.1 unix linux-x86_64 (5c6fadfb266d - 2018-03-16 18:25:33 +0100)
[19:24:35] ExePath: "/app/bin/"
[19:24:35] SystemDataPath: "/app/share/games/openclonk/"
[19:24:35] UserDataPath: "/var/home/***/.clonk/openclonk/"
[19:24:35] Command line: openclonk
[19:24:35] Couldn't find matching GLX visual
[19:24:35] Spiel deinitialisiert.
[19:24:35] Engine heruntergefahren.
```

## System

Fedora 32 Silverblue (v 32.20200605.0)
x64
GNOME v3.36.2
Wayland

OpenClonk installed [from Flathub](https://flathub.org/apps/details/org.openclonk.OpenClonk)
v8.1

device: IdeaPad 5 15ARE05 (81YQ (LENOVO_MT_81YQ_BU_idea_FM_IdeaPad 5 15ARE05))
CPU: AMD Ryzen 7 4800U with radeon graphics x16
GPU: AMD Renoir

```
$ lspci -vnn | grep VGA -A 12
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [1002:1636] (rev c1) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device [17aa:381b]
	Flags: bus master, fast devsel, latency 0, IRQ 43
	Memory at 460000000 (64-bit, prefetchable) [size=256M]
	Memory at 470000000 (64-bit, prefetchable) [size=2M]
	I/O ports at 1000 [size=256]
	Memory at fc400000 (32-bit, non-prefetchable) [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

03:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:1637]
	Subsystem: Lenovo Device [17aa:381e]
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RENOIR (DRM 3.36.0, 5.6.15-300.fc32.x86_64, LLVM 10.0.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.7
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.7
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
$ sudo lshw -C cpu
  *-cpu                     
       description: CPU
       product: AMD Ryzen 7 4800U with Radeon Graphics
       vendor: Advanced Micro Devices [AMD]
       physical id: 6
       bus info: cpu@0
       version: AMD Ryzen 7 4800U with Radeon Graphics
       serial: Null
       slot: FP6
       size: 1880MHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca cpufreq
       configuration: cores=8 enabledcores=8 threads=16
$ sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: Renoir
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: /dev/fb0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list fb
       configuration: depth=32 driver=amdgpu latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:40-3f iomemory:40-3f irq:43 memory:460000000-46fffffff memory:470000000-4701fffff ioport:1000(size=256) memory:fc400000-fc47ffff

```

## Possible problem

I guess this problem could be an issue with the fact that a relatively recent AMD GPU is used.

Other games (like SuperTuxKart or 0 A.D.) work without problems.

**Comment by lluchs** [comment] 2020-06-07 19:08
The issue is most likely missing antialiasing on XWayland, as in #137.

Try adding `MultiSampling=0` to the `[Graphics]` section in `~/.clonk/openclonk/config` which should disable antialiasing, matching the available modes in XWayland.

Alternatively, try compiling the current git master which includes a fix (i.e., it automatically disables antialiasing).

**Comment by rugk** [comment] 2020-06-13 15:32
Yep, seems to work. But well… of course antialiasing should also be made possible to work on Wayland.

**Comment by lluchs** [comment] 2020-06-30 19:35
I just pushed some commits that switches the OpenGL support library from GLEW to Epoxy, which makes OpenClonk work under Wayland. Will be part of the next release (whenever that happens...), or alternatively by building master yourself or [downloading a snapshot build](https://www.openclonk.org/snapshots/).

**Closed by lluchs** 2020-06-30 19:35 UTC
